---
title: "Misc"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

---

```{r}
# Still need to figure out what this is actually doing
if (!require(librarian)){
  remotes::install_github("DesiQuintans/librarian")
  library(librarian)
}

shelf(
  # database
  DBI, RPostgres,
  # tidyverse
  dplyr, purrr, readr, tibble, tidyr,
  # report
  DT, knitr, markdown, rmarkdown,
  # utility
  fs, glue, here, png, scales, stringr, urltools, ggplot2)
# here <- here::here

pass <- readLines("../../pwd.txt")

conn = dbConnect(
  RPostgres::Postgres(),
  dbname   = "btc",
  host     = "localhost",
  port     = 5432,
  user     = "cgrant",
  password = pass
)
knitr::opts_chunk$set(echo = T, warning = F, message = F, connection = "conn")
```


```{r query}
sql <- glue ("SELECT * FROM public.bitcoin")
res <- dbGetQuery(conn, sql)
```

```{r}
plt <- ggplot(res, aes(x=as.Date(updated), y=btc_price)) +
  geom_line(color="red", size=1) +
  ylab("BTC Price") +
  xlab("Date") +
  # scale_x_date(date_labels="%b\n%Y")
  scale_x_date(date_labels='%m-%d-%YS')
plt
```


