---
title: "second_Rmd"
output: 
  html_document:
    toc: TRUE
    code_folding: hide
editor_options:
  chunk_output_type: console
---
## YAML Header
Optional section of render at beginning of file (e.g. pandoc).  
Options written as key:value pairs.



```{r setup, include=F}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```


## Install packages
```{r packages, echo=F}
# install.packages("DBI")
# install.packages("RPostgres")
# install.packages("here")
# install.packages("glue")
# install.packages("leaflet")
# install.packages("lwgeom")
# install.packages("dplyr")
library(DBI)
library(RPostgres)
library(here)
library(glue)
library(leaflet)
library(lwgeom)
library(dplyr)
library(ggplot2)
```

## Database connection
```{r dbconn, echo=F}
conn <- DBI::dbConnect(
  RPostgres::Postgres(),
  dbname   = "personal",
  host     = "localhost",
  port     = 5432,
  user     = "cgrant",
  password = "Cougfan42!"
)

tbls <- dbListTables(conn)
```

```{r query, echo=F}
sql <- glue("SELECT * FROM checking;")


#The dbSendQuery registers the request for the data that has to be called by dbFetch
#res <- dbSendQuery(conn, sql)
#dbFetch(res)

#The dbGetQuery method returns all the query results in a dataframe. 
res <- dbGetQuery(conn, sql)
#dbDisconnect(conn)
```

## Plot for checking account credit transactions
```{r plot1, echo=F}
#headers <- names(res)

plt <- ggplot(res, aes(x=date, y=credit)) +
        geom_point()
plt
```

## Now lets filter out small credit amounts
```{r filter, echo=F}
filt_res <- filter(res, credit >= 5.0)
plt2 <- ggplot(filt_res, aes(x=date, y=credit)) +
        geom_point() +
        theme_bw() +
        ggtitle("Checking credits over time")
plt2
```


## Lets include plotly to make this interactive
```{r interact, echo=F}
library(plotly)
plt3 <- ggplotly(plt2, tooltip = c("credit"))
plt3
```


## Try to bring it all together
```{r conclusion, echo=F}
p <- dbGetQuery(conn, "SELECT * FROM savings;") %>% 
  filter(., deposit >= 5.0) %>% 
  ggplot(aes(x=date, y=deposit)) +
    geom_point()

plot <- ggplotly(p, tooltip = c("deposit"))
plot
```





